export { Hero } from './Hero';
export { NewArrivals } from './NewArrivals';
export { BannerSlider } from './BannerSlider';
export { CategoryShowcase } from './CategoryShowcase';
export { Category } from './Category';
export { TrendingProducts } from './TrendingProducts';
export { ProductCard } from './ProductCard';
export { FeaturedCollection } from './FeaturedCollection';
import { useProductStore } from '@/store';